#!/usr/bin/env bash
#
# scripts/claude_review.sh
# Run a Claude Code headless review/audit prompt and file a provenance-stamped report.
#
# Usage:
#   scripts/claude_review.sh -o reviews/claude/<slug>.md [opts] <input-file>... <<'PROMPT'
#   ...prompt text...
#   PROMPT
#
# Options:
#   -o FILE     output report path (required; convention: reviews/claude/<slug>.md)
#   -m MODEL    Claude model alias or full name; omit to use the default (sonnet)
#   -p FILE     read the prompt from FILE instead of stdin
#
# The CLI is run in non-interactive plan (read-only) mode with the repo root exposed
# via --add-dir so it can inspect the named input files headlessly.

set -eo pipefail

# Never fail silently: if `set -e` aborts on some command, report where.
trap 'rc=$?; echo "claude_review.sh: aborted at line $LINENO (exit $rc)" >&2' ERR

# The claude CLI is a `#!/usr/bin/env node` script. Non-interactive shells skip
# ~/.bashrc's nvm load, so ensure the newest nvm node is on PATH.
NODE_BIN="$(ls -d "$HOME"/.nvm/versions/node/*/bin 2>/dev/null | sort -V | tail -1 || true)"
if [ -n "$NODE_BIN" ]; then export PATH="$NODE_BIN:$PATH"; fi

MODEL="sonnet"; OUT=""; PROMPT_FILE=""   # always use Sonnet unless -m overrides
while [ $# -gt 0 ]; do
  case "$1" in
    -o) OUT="$2"; shift 2;;
    -m) MODEL="$2"; shift 2;;
    -p) PROMPT_FILE="$2"; shift 2;;
    --) shift; break;;
    -*) echo "unknown option: $1" >&2; exit 2;;
    *) break;;
  esac
done
[ -n "$OUT" ] || { echo "usage: $0 -o <out.md> [opts] <input-file>...  (prompt on stdin or -p FILE)" >&2; exit 2; }
[ $# -gt 0 ] || { echo "error: no input files given" >&2; exit 2; }

command -v claude >/dev/null || { echo "claude not found on PATH" >&2; exit 3; }
command -v node   >/dev/null || { echo "node not found on PATH (nvm not loaded)" >&2; exit 3; }
ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"

if [ -n "$PROMPT_FILE" ]; then PROMPT="$(cat "$PROMPT_FILE")"; else PROMPT="$(cat)"; fi
[ -n "$PROMPT" ] || { echo "error: empty prompt (nothing on stdin / -p file)" >&2; exit 2; }

INPUTS=("$@")
for f in "${INPUTS[@]}"; do [ -f "$f" ] || { echo "missing input file: $f" >&2; exit 2; }; done

raw="$(mktemp)"; err="$(mktemp)"
trap 'rm -f "$raw" "$err"' EXIT

# -p headless, text output, plan (read-only) permissions, repo root readable.
claude_args=(-p --output-format text --permission-mode plan --add-dir "$ROOT")
[ -n "$MODEL" ] && claude_args+=(--model "$MODEL")

# Auth: claude.ai subscription (claude login) FIRST, ANTHROPIC_API_KEY as BACKUP.
# ANTHROPIC_API_KEY, if set, overrides the login — so stash it and unset it, so the
# first attempt uses the subscription; the fallback re-sets it for API billing.
ANTHROPIC_KEY="${ANTHROPIC_API_KEY:-$(grep -oP 'ANTHROPIC_API_KEY="\K[^"]+' "$HOME/.bashrc" 2>/dev/null | tail -1 || true)}"
unset ANTHROPIC_API_KEY

_claude_try() {  # $1: sub|api ; stdout->$raw stderr->$err
  if [ "$1" = api ]; then
    printf '%s' "$PROMPT" | ANTHROPIC_API_KEY="$ANTHROPIC_KEY" claude "${claude_args[@]}" >"$raw" 2>"$err"
  else
    printf '%s' "$PROMPT" | claude "${claude_args[@]}" >"$raw" 2>"$err"
  fi
}

AUTH_MODE=""
if [ "${FORCE_API:-0}" = 1 ] && [ -n "$ANTHROPIC_KEY" ]; then
  _claude_try api && AUTH_MODE="api (forced)" || { echo "FAILED (claude, api):" >&2; sed 's/^/    /' "$err" >&2; exit 1; }
elif _claude_try sub; then
  AUTH_MODE="subscription"
elif [ -n "$ANTHROPIC_KEY" ]; then
  echo "claude: subscription failed — retrying with ANTHROPIC_API_KEY (backup)..." >&2
  _claude_try api && AUTH_MODE="api (fallback)" || { echo "FAILED (claude: subscription AND api both failed):" >&2; sed 's/^/    /' "$err" >&2; exit 1; }
else
  echo "FAILED (claude): subscription failed and no ANTHROPIC_API_KEY available for fallback." >&2
  sed 's/^/    /' "$err" >&2; exit 1
fi

# Claude -p text output is the final message only; just trim leading blank lines.
clean="$(sed '/./,$!d' "$raw")"
[ -n "$clean" ] || clean="$(cat "$raw")"

mkdir -p "$(dirname "$OUT")"
{
  printf '# %s\n\n' "$(basename "${OUT%.md}")"
  printf '> Generated by Claude Code (model `%s`, auth: %s) on %s.\n' \
    "${MODEL:-default}" "$AUTH_MODE" "$(date '+%F %T %Z')"
  printf '> Inputs (%d): %s\n\n---\n\n' "${#INPUTS[@]}" "${INPUTS[*]}"
  printf '%s\n' "$clean"
} > "$OUT"
