#!/usr/bin/env bash
#
# scripts/codex_review.sh
# Run a Codex CLI headless review/audit prompt and file a provenance-stamped report.
#
# Usage:
#   scripts/codex_review.sh -o reviews/codex/<slug>.md [opts] <input-file>... <<'PROMPT'
#   ...prompt text...
#   PROMPT
#
# Options:
#   -o FILE     output report path (required; convention: reviews/codex/<slug>.md)
#   -m MODEL    Codex model name; omit to use the CLI default
#   -p FILE     read the prompt from FILE instead of stdin
#
# Codex is agentic: it reads the named input files itself from the repo root (-C),
# in a read-only sandbox. The final review is captured via --output-last-message,
# so no stdout narration ends up in the report.

set -eo pipefail

# Never fail silently: if `set -e` aborts on some command, report where.
trap 'rc=$?; echo "codex_review.sh: aborted at line $LINENO (exit $rc)" >&2' ERR

# The codex CLI is a `#!/usr/bin/env node` script. Non-interactive shells skip
# ~/.bashrc's nvm load, so ensure the newest nvm node is on PATH.
NODE_BIN="$(ls -d "$HOME"/.nvm/versions/node/*/bin 2>/dev/null | sort -V | tail -1 || true)"
if [ -n "$NODE_BIN" ]; then export PATH="$NODE_BIN:$PATH"; fi

MODEL=""; OUT=""; PROMPT_FILE=""
while [ $# -gt 0 ]; do
  case "$1" in
    -o) OUT="$2"; shift 2;;
    -m) MODEL="$2"; shift 2;;
    -p) PROMPT_FILE="$2"; shift 2;;
    --) shift; break;;
    -*) echo "unknown option: $1" >&2; exit 2;;
    *) break;;
  esac
done
[ -n "$OUT" ] || { echo "usage: $0 -o <out.md> [opts] <input-file>...  (prompt on stdin or -p FILE)" >&2; exit 2; }
[ $# -gt 0 ] || { echo "error: no input files given" >&2; exit 2; }

command -v codex >/dev/null || { echo "codex not found on PATH" >&2; exit 3; }
command -v node  >/dev/null || { echo "node not found on PATH (nvm not loaded)" >&2; exit 3; }
ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"

if [ -n "$PROMPT_FILE" ]; then PROMPT="$(cat "$PROMPT_FILE")"; else PROMPT="$(cat)"; fi
[ -n "$PROMPT" ] || { echo "error: empty prompt (nothing on stdin / -p file)" >&2; exit 2; }

INPUTS=("$@")
for f in "${INPUTS[@]}"; do [ -f "$f" ] || { echo "missing input file: $f" >&2; exit 2; }; done

last="$(mktemp)"; log="$(mktemp)"
trap 'rm -f "$last" "$log"' EXIT

codex_args=(exec --sandbox read-only -C "$ROOT" --skip-git-repo-check --ephemeral
            --color never --output-last-message "$last")
[ -n "$MODEL" ] && codex_args+=(--model "$MODEL")

# Auth: ChatGPT subscription (codex login) FIRST, OpenAI API key as BACKUP.
# Codex ignores $OPENAI_API_KEY when ChatGPT auth is stored, but honors $CODEX_HOME —
# so the API key gets its own auth home (~/.codex-apikey), provisioned on first use.
OPENAI_KEY="${OPENAI_API_KEY:-$(grep -oP 'OPENAI_API_KEY="\K[^"]+' "$HOME/.bashrc" 2>/dev/null | tail -1 || true)}"
APIHOME="$HOME/.codex-apikey"

_codex_try() {  # $1: sub|api ; last->$last log->$log
  local home="$HOME/.codex"
  if [ "$1" = api ]; then
    home="$APIHOME"
    mkdir -p "$APIHOME"
    if [ ! -f "$APIHOME/auth.json" ]; then
      printf '%s' "$OPENAI_KEY" | CODEX_HOME="$APIHOME" codex login --with-api-key >/dev/null 2>&1 || true
    fi
    # Codex uses the Responses API; many API projects lack Responses access to the
    # subscription models (gpt-5.5*), so default to one that IS Responses-accessible.
    # Override with CODEX_API_MODEL or -m once your project has access to another.
    printf 'model = "%s"\n' "${CODEX_API_MODEL:-gpt-5.2}" > "$APIHOME/config.toml"
  fi
  CODEX_HOME="$home" codex "${codex_args[@]}" "$PROMPT" </dev/null >"$log" 2>&1
}

AUTH_MODE=""
if [ "${FORCE_API:-0}" = 1 ] && [ -n "$OPENAI_KEY" ]; then
  _codex_try api && AUTH_MODE="api (forced)" || { echo "FAILED (codex, api):" >&2; sed 's/^/    /' "$log" >&2; exit 1; }
elif _codex_try sub; then
  AUTH_MODE="subscription"
elif [ -n "$OPENAI_KEY" ]; then
  echo "codex: subscription failed — retrying with OPENAI_API_KEY (backup, CODEX_HOME=$APIHOME)..." >&2
  _codex_try api && AUTH_MODE="api (fallback)" || { echo "FAILED (codex: subscription AND api both failed):" >&2; sed 's/^/    /' "$log" >&2; exit 1; }
else
  echo "FAILED (codex): subscription failed and no OPENAI_API_KEY available for fallback." >&2
  sed 's/^/    /' "$log" >&2; exit 1
fi

# The clean final review is in --output-last-message; fall back to the run log if empty.
clean="$(sed '/./,$!d' "$last")"
[ -n "$clean" ] || clean="$(sed '/./,$!d' "$log")"

mkdir -p "$(dirname "$OUT")"
{
  printf '# %s\n\n' "$(basename "${OUT%.md}")"
  printf '> Generated by Codex CLI (model `%s`, auth: %s) on %s.\n' \
    "${MODEL:-default}" "$AUTH_MODE" "$(date '+%F %T %Z')"
  printf '> Inputs (%d): %s\n\n---\n\n' "${#INPUTS[@]}" "${INPUTS[*]}"
  printf '%s\n' "$clean"
} > "$OUT"
